#!/usr/bin/env ruby
$:.unshift(File.dirname(__FILE__) + "/../../lib")
require 'git-style-binary/command'

GitStyleBinary.command do
  short_desc "do something with categories"
  banner <<-EOS
Usage: #{command.full_name} #{all_options_string}

Does something with categories

EOS
  run do |command|
    puts "does something with categories"
  end
end

