#!/usr/bin/env ruby
$:.unshift(File.dirname(__FILE__) + "/../../lib")

require 'git-style-binary/command'
GitStyleBinary.primary do
  version "#{command.full_name} 0.0.1 (c) 2009 Nate Murray - local"

  options_description = <<-EOF
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
  EOF
  opt :test_primary, options_description, :type => String

  run do |command|
    puts "Primary Options: #{command.opts.inspect}"
  end
end

# OR

# require 'git-style-binary/primary'
# command = GitStyleBinary::primary("wordpress") do
#   version "#{$0} 0.0.1 (c) 2009 Nate Murray"
#   banner <<-EOS
# usage: #{$0} #{all_options.collect(:&to_s).join(" ")} COMMAND [ARGS]
#
# The wordpress subcommands commands are:
# {subcommand_names.pretty_print}
#
# See 'wordpress help COMMAND' for more information on a specific command.
# EOS
#   opt :verbose,  "verbose", :default => false
#   opt :dry,      "dry run", :default => false
#   opt :test_global, "a basic global string option", :type => String
# end
