#!/bin/env ruby
$:.unshift(File.dirname(__FILE__) + "/../../lib")
require 'git-style-binary/command'

command = GitStyleBinary::command do # OR command = GitStyleBinary::command("post", :primary => "wordpress") do
  banner <<-EOS
usage: #{$0} #{all_options.collect(:&to_s).join(" ")} COMMAND [ARGS]

The wordpress subcommands commands are:
#{subcommands.pretty_print}

See 'wordpress help COMMAND' for more information on a specific command.
EOS
  opt :blog,     "short name of the blog to use", :default => 'default'
  opt :category, "tag/category. specify multiple times for multiple categories", :type => String, :multi => true
  opt :title,    "title for the post", :required => true
  opt :type,     "type of the content [html|xhtml|text]", :default => 'html', :type => String
end
command.die :type, "type must be one of [html|xhtml|text]" unless opts[:type] =~ /^(x?html|text)$/i

puts "Global options:      #{command.global_opts.inspect}"
puts "Subcommand name:     #{command.cmd.inspect}"
puts "Subcommand options:  #{command.cmd_opts.inspect}"
puts "Merged opts:         #{command.opts.inspect}"
puts "Remaining arguments: #{command.argv.inspect}"
